system:
    default:
        enhanced_relation_list:
            base_template: '@ezdesign/enhanced_relation_list/base_template.html.twig'
            attribute_templates:
                -
                    template: '@ezdesign/enhanced_relation_list/erl_attributes.html.twig'
                    priority: 0
            attribute_definition_templates:
                -
                    template: '@ezdesign/enhanced_relation_list/erl_attributes_definition.html.twig'
                    priority: 0
        fielddefinition_edit_templates:
            -
                template: '@ezdesign/enhanced_relation_list/content_type/field_types.html.twig'
                priority: 0
        field_templates:
            -
                template: '@ezdesign/enhanced_relation_list/content_fields.html.twig'
                priority: 0
        content_view:
            element_simple_link:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: '@ezdesign/enhanced_relation_list/simple_link.html.twig'
                    match: true
        fielddefinition_settings_templates:
            - {template: '@ezdesign/enhanced_relation_list/fielddefinition_settings.html.twig', priority: 0}
