services:
    IntProg\EnhancedRelationListBundle\Form\Type\EnhancedRelationListType:
        arguments:
            - '@ezpublish.api.service.content'
            - '@IntProg\EnhancedRelationListBundle\Service\RelationAttributeRepository'
        tags:
            - { name: form.type }

    IntProg\EnhancedRelationListBundle\Form\Type\EnhancedRelationListFieldDefinitionGroupsType:
        arguments:
            - '@ezpublish.api.service.language'
            - '$languages$'
        tags:
            - { name: form.type }

    IntProg\EnhancedRelationListBundle\Form\Type\EnhancedRelationListFieldDefinitionAttributesType:
        arguments:
            - '@IntProg\EnhancedRelationListBundle\Service\RelationAttributeRepository'
            - '@ezpublish.api.service.language'
            - '$languages$'
        tags:
            - { name: form.type }
