services:
    IntProg\EnhancedRelationListBundle\Form\Type\EnhancedRelationListType:
        arguments:
            - '@ezpublish.api.service.content'
            - '@IntProg\EnhancedRelationListBundle\Service\RelationAttributeRepository'
        tags:
            - { name: form.type }

    IntProg\EnhancedRelationListBundle\Form\Type\EnhancedRelationListFieldDefinitionGroupsType:
        lazy: true
        autowire: true
        tags:
            - { name: form.type }

    IntProg\EnhancedRelationListBundle\Form\Type\EnhancedRelationListFieldDefinitionAttributesType:
        arguments:
            $attributeRepository: '@IntProg\EnhancedRelationListBundle\Service\RelationAttributeRepository'
        lazy: true
        autowire: true
        tags:
            - { name: form.type }
