services:
    IntProg\EnhancedRelationListBundle\Service\RelationAttributeRepository:
        arguments:
            - []

    IntProg\EnhancedRelationListBundle\Templating\Twig\Extension\RelationAttributeExtension:
        arguments:
            - '@intprog.enhanced-relation-list.templating.attribute_block_renderer'
            - '@ezpublish.persistence.connection'
            - '@ezpublish.api.service.content'
        tags:
            - { name: twig.extension }

    intprog.enhanced-relation-list.ezadminui.component.javascripts:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        public: false
        arguments:
            $template: '@@ezdesign/enhanced_relation_list/assets/javascripts.html.twig'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'script-body' }
    intprog.enhanced-relation-list.ezadminui.component.stylesheets:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        public: false
        arguments:
            $template: "@@ezdesign/enhanced_relation_list/assets/stylesheets.html.twig"
        tags:
            - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }
