services:
    intprog.enhanced-relation-list.templating.attribute_block_renderer.twig:
        class: IntProg\EnhancedRelationListBundle\Templating\Twig\AttributeBlockRenderer
        calls:
            - [setTwig, ['@twig']]
        lazy: true
        autowire: true

    intprog.enhanced-relation-list.templating.attribute_block_renderer:
        alias: intprog.enhanced-relation-list.templating.attribute_block_renderer.twig
